apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-install-{{ template "kibana.fullname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.setup.annotations }}
    {{- range $key, $value := .Values.setup.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
