apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pre-delete-{{ template "kibana.fullname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- if .Values.delete.annotations }}
    {{- range $key, $value := .Values.delete.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
